# Default values for drupal-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: drupal
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10"

drupal:
  url: "dev.drupal.local"
  environment: "dev"
  cronSchedule: "*/20 * * * *"
  pvcSize: "5Gi"
  root: "/var/www/html"
  pvc:
    enabled: true
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: "5Gi"
    storageClass: ""
  database:
    host: "mysql"
    port: 3306
    username: "drupal"
    password: "drupal"
    database: "drupal"
    prefix: ""

shield:
  enabled: false
  username: ""
  password: ""

memcached:
  enabled: false

varnish:
  enabled: false
  image: "varnish:6.5"
  port: 8080
  configFile: "default.vcl"

cron:
  enabled: false
  schedule: "*/20 * * * *"
  command: "drush cron"

newrelic:
  enabled: true

# Pre deployment commands
initCommand: ["/bin/bash", "-c"]
initCommandArgs: ["drush updb -y && drush cim -y && drush cim -y && drush cr"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

#securityContext:
#   capabilities:
#     drop:
#     - ALL
##   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 33

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 6


readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 20

probe:
  # Type can be http or tcp. Default is http.
  # The http probe requires a success response code, so may be more sensitive to errors in the application.
  type: "http"
  injectScript: true
  path: "/liveness.php"
  script: "<?php echo 'OK-' . time(); ?>"
